name: shadow_game
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flame: ^1.17.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  go_router: ^13.2.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/level_one/
    - assets/images/level_one/animations/
    - assets/images/level_one/chest/
    - assets/images/level_one/door/
    - assets/images/level_one/spider/
    - assets/images/level_one/trees/
    - assets/images/lobby/
    - assets/images/player/
    - assets/images/player/stay/
    - assets/images/player/attack/
    - assets/images/player/cut/
    - assets/images/player/jump/
    - assets/images/player/dance/
    - assets/images/player/walk/
    - assets/images/shadow/sit/
    - assets/images/shadow/wait/
    - assets/images/shadow/walk/
    - assets/images/shared/
    - assets/images/shared/damage/
    - assets/images/shared/endurance/
    - assets/images/shared/life/
    - assets/images/shared/speed/
    - assets/images/shared/icons/
