name: shadow_game
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  flutter_spinkit: ^5.2.1
  go_router: ^13.2.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/level_one/
    - assets/imgs/level_one/animations/
    - assets/imgs/level_one/chest/
    - assets/imgs/level_one/door/
    - assets/imgs/level_one/spider/
    - assets/imgs/level_one/trees/
    - assets/imgs/lobby/
    - assets/imgs/player/
    - assets/imgs/shadow/
    - assets/imgs/shared/
    - assets/imgs/shared/damage/
    - assets/imgs/shared/endurance/
    - assets/imgs/shared/life/
    - assets/imgs/shared/speed/